{{- if .Values.defaultLogging.enabled -}}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "mia-logging.fullname" . | quote }}
  labels: &Labels
    {{- include "mia-logging.labels" . | nindent 4 }}
  {{- with .Values.deploy.annotations }}
  annotations: &Annotations
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  loggingRef: ""
  flowConfigCheckDisabled: false
  flowConfigOverride: ""
  controlNamespace: {{ .Release.Namespace | quote }}
  fluentbit:
    tls:
      enabled: false
    labels:
      {{- include "mia-logging.selectorLabels" . | nindent 6 }}
    image:
      repository: {{ include "mia-logging.fluentbitImageName" . | quote }}
      tag: {{ include "mia-logging.fluentbitImageVersion" . | quote }}
    filterKubernetes:
      Buffer_Size: "0"
      Merge_Log: "Off"
      Labels: "On"
      Annotations: "On"
      K8S-Logging.Exclude: "On"
    network:
      connectTimeout: 15
      keepalive: true
      keepaliveIdleTimeout: 10
      keepaliveMaxRecycle: 50
    inputTail:
      Path: {{ .Values.defaultLogging.fluentbit.logFilesPattern | quote }}
      Mem_Buf_Limit: {{ .Values.defaultLogging.fluentbit.memBufLimit | quote }}
      Refresh_Interval: "30"
      Rotate_Wait: "30"
    positiondb:
      hostPath:
        path: "/var/log/logging-operator"
    enableUpstream: {{ include "mia-logging.fluentbitEnableUpstream" . }}
    metrics:
      serviceMonitor: {{ .Values.enableServiceMonitor }}
      prometheusAnnotations: false
      port: 2020
      path: "/api/v1/metrics/prometheus"
      timeout: "15s"
      interval: "30s"
    {{- with .Values.defaultLogging.fluentbit.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    security:
      roleBasedAccessControlCreate: true
      podSecurityPolicyCreate: {{ .Values.podSecurityPolicyEnabled }}
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        privileged: false
        capabilities:
          drop:
            - "all"
      podSecurityContext:
        {{- include "mia-logging.fluentbitUserId" . | nindent 8 }}
        runAsGroup: 11000
        fsGroup: 12000
    {{- with .Values.defaultLogging.fluentbit.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentbit.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentbit.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentbit.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  fluentd:
    tls:
      enabled: false
    labels:
      {{- include "mia-logging.selectorLabels" . | nindent 6 }}
    image:
      repository: {{ include "mia-logging.fluentdImageName" . | quote }}
      tag: {{ include "mia-logging.fluentdImageVersion" . | quote }}
    scaling:
      replicas: {{ include "mia-logging.fluentdReplicas" . }}
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: {{ .Values.defaultLogging.fluentd.bufferStorage | quote }}
    livenessDefaultCheck: true
    readinessDefaultCheck:
      bufferFreeSpaceThreshold: 80
    metrics:
     serviceMonitor: {{ .Values.enableServiceMonitor }}
     prometheusAnnotations: false
     port: 24231
     path: "/metrics"
     timeout: "15s"
     interval: "30s"
    {{- with .Values.defaultLogging.fluentd.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    security:
      roleBasedAccessControlCreate: true
      podSecurityPolicyCreate: {{ .Values.podSecurityPolicyEnabled }}
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        privileged: false
        capabilities:
          drop:
            - "all"
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
    {{- with .Values.defaultLogging.fluentd.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentd.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentd.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.defaultLogging.fluentd.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
