apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mia-logging.fullname" . | quote }}
  labels:
    {{- include "mia-logging.labels" . | nindent 4 }}
  {{- with .Values.deploy.annotations }}
  annotations: &Annotations
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels: &Labels
      {{- include "mia-logging.selectorLabels" . | nindent 6 }}
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: *Labels
      {{- with .Values.deploy.annotations }}
      annotations: *Annotations
      {{- end }}
    spec:
      serviceAccountName: {{ include "mia-logging.serviceAccountName" . | quote }}
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 60
      {{- with .Values.deploy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "mia-logging.fullname" . | quote }}
          image: {{ include "mia-logging.image" . | quote }}
          {{- with .Values.deploy.resources }}
          args:
            - "-enable-leader-election=true"
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: "web"
              containerPort: 8080
              protocol: "TCP"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - "all"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 11000
        fsGroup: 12000
      {{- with .Values.deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
