apiVersion: batch/v1
kind: Job
metadata:
  name:  patch-webhooks
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "mia-monitoring.hooks.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name:  {{ include "mia-monitoring.hooks.fullname" . | quote }}
      labels:
        {{- include "mia-monitoring.hooks.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mia-monitoring.hooks.serviceAccountName" . | quote }}
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 60
      {{- with .Values.deploy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "mia-monitoring.hooks.fullname" . | quote }}
          image: {{ include "mia-monitoring.hooks.image" . | quote }}
          args:
            {{- include "mia-monitoring.hooks.patchArgs" . | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - "all"
      restartPolicy: "OnFailure"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 11000
        fsGroup: 12000
      {{- with .Values.deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
