{{- if .Values.cortexProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cortex-list-namespaces
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cortex-list-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cortex-list-namespaces
subjects:
- kind: ServiceAccount
  name: cortex
  namespace: cortex
{{- end }}
