{{- if .Values.podSecurityPolicyEnabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "mia-monitoring.nodeExporter.fullname" . | quote }}
  labels:
    {{- include "mia-monitoring.nodeExporter.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "runtime/default"
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  "runtime/default"
spec:
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - "ALL"
  volumes:
    - "secret"
    - "hostPath"
  allowedHostPaths:
    - pathPrefix: "/proc"
      readOnly: true
    - pathPrefix: "/sys"
      readOnly: true
    - pathPrefix: "/"
      readOnly: true
  hostPorts:
  - min: 9100
    max: 9100
  hostNetwork: true
  hostIPC: false
  hostPID: true
  runAsUser:
    rule: "MustRunAs"
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "MustRunAs"
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: "MustRunAs"
    ranges:
      - min: 1
        max: 65535
{{- end -}}
