apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mia-monitoring.hooks.roleName" . | quote }}
  labels:
    {{- include "mia-monitoring.hooks.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync,PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    helm.sh/hook: "pre-install,pre-upgrade,post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-5"
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingwebhookconfigurations"
      - "mutatingwebhookconfigurations"
    verbs:
      - "get"
      - "update"
{{- if .Values.podSecurityPolicyEnabled }}
  - apiGroups:
      - "policy"
    resources:
      - "podsecuritypolicies"
    verbs:
      - "use"
    resourceNames:
      - {{ include "mia-monitoring.hooks.fullname" . | quote }}
{{- end -}}
