apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mia-monitoring.hooks.roleName" . | quote }}
  labels:
    {{- include "mia-monitoring.hooks.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync,PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    helm.sh/hook: "pre-install,pre-upgrade,post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-5"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: {{ include "mia-monitoring.hooks.roleName" . | quote }}
subjects:
  - kind: "ServiceAccount"
    name: {{ include "mia-monitoring.hooks.serviceAccountName" . | quote }}
    namespace: {{ .Release.Namespace | quote }}
