{{- if .Values.service.enableTLS -}}
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "mia-traefik-ingress.defaultTLSOptionName" . | quote }}
  labels:
    {{- include "mia-traefik-ingress.labels" . | nindent 4 }}
spec:
  strictSni: {{ .Values.tlsStrictSni }}
  {{- include "mia-traefik-ingress.defaultTlsOptionSpec" . | nindent 2 }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "mia-traefik-ingress.oldTLSOptionName" . | quote }}
  labels:
    {{- include "mia-traefik-ingress.labels" . | nindent 4 }}
spec:
  strictSni: true
  {{- include "mia-traefik-ingress.oldTlsOptionSpec" . | nindent 2 }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "mia-traefik-ingress.intermediateTLSOptionName" . | quote }}
  labels:
    {{- include "mia-traefik-ingress.labels" . | nindent 4 }}
spec:
  strictSni: true
  {{- include "mia-traefik-ingress.intermediateTlsOptionSpec" . | nindent 2 }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "mia-traefik-ingress.modernTLSOptionName" . | quote }}
  labels:
    {{- include "mia-traefik-ingress.labels" . | nindent 4 }}
spec:
  strictSni: true
  {{- include "mia-traefik-ingress.modernTlsOptionSpec" . | nindent 2 }}
{{- end -}}
