apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mia-traefik-ingress.roleName" . | quote }}
  labels:
    {{- include "mia-traefik-ingress.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "endpoints"
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - "ingresses"
      - "ingressclasses"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - "ingresses/status"
    verbs:
      - "update"
  - apiGroups:
      - "traefik.containo.us"
    resources:
      - "ingressroutes"
      - "ingressroutetcps"
      - "ingressrouteudps"
      - "middlewares"
      - "middlewaretcps"
      - "tlsoptions"
      - "tlsstores"
      - "traefikservices"
      - "serverstransports"
    verbs:
      - "get"
      - "list"
      - "watch"
# from here the crd changes
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "list"
      - "watch"
  - apiGroups:
      - "gateway.networking.k8s.io"
    resources:
      - "gatewayclasses"
      - "gateways"
      - "httproutes"
      - "tcproutes"
      - "tlsroutes"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "gateway.networking.k8s.io"
    resources:
      - "gatewayclasses/status"
      - "gateways/status"
      - "httproutes/status"
      - "tcproutes/status"
      - "tlsroutes/status"
    verbs:
      - "update"
{{- if .Values.podSecurityPolicyEnabled }}
  - apiGroups:
      - "policy"
    resources:
      - "podsecuritypolicies"
    resourceNames:
      - {{ include "mia-traefik-ingress.fullname" . }}
    verbs:
      - "use"
{{- end }}
