apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mia-monitoring.prometheus.fullname" . | quote }}
  labels:
    {{- include "mia-monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mia-monitoring.prometheus.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  jobLabel: "app.kubernetes.io/name"
  podMetricsEndpoints:
  - path: /metrics
    port: web
    metricRelabelings:
    - action: keep
      regex: prometheus.*
      sourceLabels:
      - __name__
  - path: /metrics
    port: reloader-web
    metricRelabelings:
    - action: keep
      regex: reloader.*
      sourceLabels:
      - __name__
